version: '3.3'

services:
  nginx:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app