version: '3.3'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.nginx
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.server
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.client
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app