version: '3.3'

services:
  nginx:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
    build:
      dockerfile: Dockerfile
      context: "./api"
    volumes:
      - /app/node_modules
      - ./api:/app
    expose:
      - '3001' 
  client:
    image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    expose:
      - '3000'