version: '3.3'

services:
  nginx:
    image: 726562207460.dkr.ecr.us-west-1.amazonaws.com/birthsound-nginx:latest
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    image: 726562207460.dkr.ecr.us-west-1.amazonaws.com/birthsound-server:latest
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    image: 726562207460.dkr.ecr.us-west-1.amazonaws.com/birthsound-client:latest
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app