version: '3.3'


services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.develop
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.develop
      context: "./server"
    expose:
      - '3001'
    volumes:
      - /app/node_modules
      - ./server:/app
      
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.develop
      context: ./client
    expose:
      - '3000'
    volumes:
      - /app/node_modules
      - ./client:/app
